### ISSUE TITLE
UpnpSendAdvertisement() expiration limit

### ISSUE THREAD

**Issue by gburca** [mrjimenez/pupnp#12]
When UpnpSendAdvertisement() is called with an expiration age of 60, the advertisements are sent continuously, one right after the other, instead of 60s apart. That's because TimeThreadSchedule() is called with:

```
#define AUTO_ADVERTISEMENT_TIME 30
TimerThreadSchedule(..., (Exp / 2) - AUTO_ADVERTISEMENT_TIME, REL_SEC, ...)
```

To truly send an advertisement every 60s, the caller would have to ask for 180s. Values less than 60 would schedule events in the past.

**Comment by ffontaine** [comment]
You're completely right, there is an issue however UPnP UDA (https://openconnectivity.org/resources/specifications/upnp/architectural-documents) defines that the duration of advertisements should be greater than or equal to 1800 seconds moreover advertisements should be refreshed before the end of their duration. So I think that one possible fix would be to replace:
```
if( Exp < 1 )
Exp = DEFAULT_MAXAGE;
```
by
```
if( Exp <= AUTO_ADVERTISEMENT_TIME * 2 )
Exp = DEFAULT_MAXAGE;
```
inside the UpnpSendAdvertisementLowPower function.
However, this will change the current pupnp behaviour and perhaps some applications are already using the 60 value to send advertisements continuously (even if this seems a bad idea). So I would like to have the feedback of @mrjimenez.

**Comment by gburca** [comment]
Using a value of 60 results in a DOS type flood of packets on the network. libupnp pumps advertisements out as fast as it can. I can't imagine anyone needing to flood the network with SSDP packets for legitimate purposes.

Your suggestion is sensible. I would however use `(AUTO_ADVERTISEMENT_TIME + 1) * 2` instead of `DEFAULT_MAXAGE` to more closely match what the user requested, but either value would eliminate the possibility of timers set in the past, or packet floods, which is the root issue here.

**Comment by mrjimenez** [comment]
Hi Fabrice,

I think your solution is ok, since the problem Gabriel reports is serious. The change is necessary, even if it breaks some applications, which would already be broken as explained in Gabriel's last comment.

So please, go ahead.

Regards!

**Comment by ffontaine** [comment]
OK, I sent PR #13 by by implementing the suggestion from Gabriel.

**Comment by ffontaine** [comment]
PR #13 has been merged in f38fc52d9b613401cbd923a4baa5bd7025825ab7 so I will close this issue. @mrjimenez, is it time for a new release as latest commits fixed some CVEs?

**Comment by mrjimenez** [comment]
Fabrice,


On Mon, Dec 19, 2016 at 1:44 PM, Fabrice Fontaine <notifications@github.com>
wrote:

> PR #13 <https://github.com/mrjimenez/pupnp/pull/13> has been merged in
> f38fc52
> <https://github.com/mrjimenez/pupnp/commit/f38fc52d9b613401cbd923a4baa5bd7025825ab7>
> so I will close this issue. @mrjimenez <https://github.com/mrjimenez>, is
> it time for a new release as latest commits fixed some CVEs?
>

I am ok with that, do you mind doing the release?

Regards,
Marcelo.

**Comment by ffontaine** [comment]
Marcelo, I made the release, can you update the sourceforge website? Thanks

**Comment by mrjimenez** [comment]
Ok, just updated the repos, will put the tar on the site right now.

Thank you very much, Fabrice!

Regards,
Marcelo.
