### ISSUE TITLE
Enable IPv6 by default?

### ISSUE THREAD

**Issue by ffontaine** [mrjimenez/pupnp#24]
Should we enable IPv6 by default (at least on version 1.8.x and perhaps also on version 1.6.x)? Most of the systems should now support IPv6.

**Comment by v00d00** [comment]
Yes please!

**Comment by mrjimenez** [comment]
It's ok on 1.8.x. Not sure about 1.6.x.

**Comment by ffontaine** [comment]
OK, we should do it only on 1.8.x to avoid breaking anything on 1.6.x.
