### ISSUE TITLE
Apply MD5 impmplementation with public-domain version to branch 1.6.x?

### ISSUE THREAD

**Issue by ffontaine** [mrjimenez/pupnp#28]
Should we apply the commit 9b9a310118a9523c72db939939a326dd9e60fa4b to branch-1.6.x and so move the entry in ChangeLog from 1.8.1 to 1.6.22?

**Comment by mrjimenez** [comment]
Yes, seems fair.

**Comment by ffontaine** [comment]
OK done by 3d16c35d37fd649a498eb57a573bda0b7d7b1e5f and 438c80db99749d51a216a3b6c9ed244b74614ce4
