### ISSUE TITLE
New 1.6 Release

### ISSUE THREAD

**Issue by v00d00** [mrjimenez/pupnp#37]
Hi,

Please cut a new 1.6 release (in addition to the 1.8 release).

I would like a release with the fixed tests for https://bugs.gentoo.org/show_bug.cgi?id=334859

Thanks,

Ian

**Comment by v00d00** [comment]
Any update?

**Comment by mrjimenez** [comment]
Hi Ian,

I am ok with a new release, I am just too overwhelmed with work to stop and do it now.

Any volunteer?

Regards,
Marcelo.

**Comment by mrjimenez** [comment]
Released!

**Comment by v00d00** [comment]
Awesome!
