### ISSUE TITLE
MacOS build fails

### ISSUE THREAD

**Issue by Tibbs** [mrjimenez/pupnp#45]
Hi,

I'm trying to build pupnp on Mac, but I'm getting errors. 
Could you help with this? Thanks!

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libupnp-1.8.a(libupnp_1_8_la-inet_pton.o) has no symbols
libtool: link: ranlib .libs/libupnp-1.8.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: .libs/libupnp-1.8.a(libupnp_1_8_la-inet_pton.o) has no symbols
/usr/local/bin/gsed: can't read Files/Mirror/gerbera/pupnp-release-1.8.1/ixml/libixml-1.8.la: No such file or directory

**Comment by mrjimenez** [comment]
Hi Tibbs,

The file ./upnp/src/inet_pton.c is completely commented out unless you are compiling it for WIN32. For some reason, the Mac linker is complaining, but the linux linker here is not.

I can suggest you two things:

1. Come up with some configure time variable and use an "if" in ./upnp/Makefile.am to exclude inet_pton.c from beeing compiled: 
```
if WIN32
# inet_pton (needed on Win32, compiles to nothing elsewhere)
libupnp_1_8_la_SOURCES += \
        src/inet_pton.c \
        src/inc/inet_pton.h
endif
```
2. Delete the previous code snippet from ./upnp/Makefile.am and see if that solves the issue.

I must admit I would rather see a patch with the first option ;)

Regards,
Marcelo.

**Comment by Tibbs** [comment]
It worked! Thank you very much

**Comment by mrjimenez** [comment]
Is there a Mac user that could generate and test a patch for this?

I cannot test it here, no Mac around.

I'd like to close this issue, it's been open for too long.

Regards,
Marcelo.

**Comment by elmodaddyb** [comment]
@mrjimenez 

I pulled the latest **master** branch and was able to `./configure && make` without any special changes on `macOS Sierra 10.12.6` with: 

`Darwin Kernel Version 16.7.0:  root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`

**Is there any steps in particular to try to reproduce the failure?**

_I successfully compiled `gerbera + pupnp-release-1.8.1`_

**Comment by mrjimenez** [comment]
Hi Eamonn,

Thank you for your attention. I'll close the issue, then.

Best regards,
Marcelo.
