### ISSUE TITLE
UpnpFileInfo weirdness on ARM

### ISSUE THREAD

**Issue by v00d00** [mrjimenez/pupnp#51]
For some reason, running the below on ARM is giving me the output below.

Code snippet
```
    off_t temp = 1024;
    log_debug(">>> TEMP %d\n", temp);
    UpnpFileInfo_set_FileLength(info, temp); 
    log_debug(">>> SIZE %jd\n", (intmax_t)UpnpFileInfo_get_FileLength(info));
```
Output
```
2017-08-13 14:59:02   DEBUG: [src/web_request_handler.cc:101] get_info(): >>> TEMP 1024
2017-08-13 14:59:02   DEBUG: [src/web_request_handler.cc:103] get_info(): >>> SIZE 1
```

Ive looked at the code, and I have no clue, as it appears to just assingn and read from a struct... and it appears to be fine on AMD64.

**Comment by ukleinek** [comment]
if you provide a complete compilable example I can look into that

**Comment by ukleinek** [comment]
Did you add the LFS stuff to your compile flags?

I see:

    $ cat lala.c 
    #include <inttypes.h>
    #include <stdio.h>
    #include <stdlib.h>
    
    #include <upnp.h>
    
    int main(int argc, char **argv)
    {
    	UpnpFileInfo *info = malloc(1000);
    
    	off_t temp = 1024;
    
    	UpnpFileInfo_set_FileLength(info, temp); 
    
    	printf(">>> SIZE %jd\n", (intmax_t)UpnpFileInfo_get_FileLength(info));
    }
  
    $ gcc -pthread -I/usr/include/upnp-1.8 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 lala.c -pthread -lupnp-1.8 -lixml-1.8 -o lala
    $ ./lala
    >>> SIZE 1024

    $ gcc -pthread -I/usr/include/upnp-1.8 lala.c -pthread -lupnp-1.8 -lixml-1.8 -o lala
    $ ./lala
    >>> SIZE -1226143852

**Comment by v00d00** [comment]
Hmmm perhaps not! I will confirm tomorrow! Thanks for the suggestion

**Comment by v00d00** [comment]
That fixed it, thanks @ukleinek!

**Comment by ukleinek** [comment]
@mrjimenez That's the kind of problem that happens if off_t is part of the API.

**Comment by mrjimenez** [comment]
Lets fix it.
