### ISSUE TITLE
off_t being part of the API results in headaches

### ISSUE THREAD

**Issue by ukleinek** [mrjimenez/pupnp#52]
As could be seen in #51 it is important that a program that makes use of libupnp is compiled using the same settings for LFS as libupnp itself.

I don't know how to best catch this kind of error (or better yet, let libupnp make the right thing independent of the settings for the using program).

Suggestions welcome

**Comment by v00d00** [comment]
I found this an interesting read: http://ac-archive.sourceforge.net/largefile/off_t_headers.html

Alternatively we could we simply use unit64_t instead?

**Comment by mrjimenez** [comment]
I like that solution. The author also comments on using int64_t, but he also discourages it because it may hide seek offset problems. If we must have off_t in the API, the proper solution is the first one, don't let anyone compile against the lib without large file support. Throwing an error at compile/configure time seems ok to me.

**Comment by v00d00** [comment]
So those checks are already present:

AC_SYS_LARGEFILE_SENSITIVE is commented out:
https://github.com/mrjimenez/pupnp/blob/57cf7774e15f2db0a62039065a84463a53b7cd80/configure.ac#L408

UpnpGlobal.h has the check:
https://github.com/mrjimenez/pupnp/blob/02f6b710ad7e108014787db433ab94d698bbd01e/upnp/inc/UpnpGlobal.h#L10

Does it simply need commenting?

**Comment by v00d00** [comment]
Seems it was commented in "Largefile support" https://github.com/mrjimenez/pupnp/commit/f1cc7db79d3e990e2b4a8485445cf73b0c0c7a80.

I am assuming this means that `MYLIB_LARGEFILE_SENSITIVE` will never be defined, so maybe change the check to simply : `#if _FILE_OFFSET_BITS+0 != 64`

**Comment by ukleinek** [comment]
I'm working on a more robust solution, give me some more time
