### ISSUE TITLE
Time to publish 1.8.x on sourceforge?

### ISSUE THREAD

**Issue by ffontaine** [mrjimenez/pupnp#55]
Dear Marcelo,

Should we publish the 1.8.x versions on https://sourceforge.net/projects/pupnp/files?

Best Regards,

Fabrice

**Comment by mrjimenez** [comment]
Hi Fabrice,

I think we should publish them. If no one is opposed to, I can do it next week.

Regards,
Marcelo.

**Comment by ffontaine** [comment]
Dear Roberto,

Could I kindly remind you to publish the versions on sourceforge?

Best Regards,

Fabrice

**Comment by mrjimenez** [comment]
Sure, I am very sorry. I'll do it right now.

Thank you for reminding me.

Regrads,
Marcelo.

**Comment by ffontaine** [comment]
Dear Roberto,

Why did you change the name and the type of the archive?
Previously, it was **lib**upnp-1.6.22.**tar.bz2**, now it is **p**upnp-**release**-1.8.2.**zip**.
Moreover, previously, the configure file was in the tar.bz2, now we have to call the bootstrap script.

Best Regards,

Fabrice

**Comment by mrjimenez** [comment]
Hi Fabrice,

I have uploaded the file that was released on Github, I undestood that this was what you wanted, but I can generate a different file using the old standard, no problems.

Regards,
Marcelo.

**Comment by ffontaine** [comment]
Yes, it would be great to keep the old standard so my buildroot patch to add 1.8.x version will keep the same standardfor 1.6.x and 1.8.x. I could also update the buildroot package to retrieve the versions from github instead of sourceforge but we already had a discussion on "sourceforge vs github" (https://github.com/mrjimenez/pupnp/issues/14) so I think we should keep using sourceforge.

**Comment by mrjimenez** [comment]
Hi Fabrice,

Its done, please tell me if you find any problem.

Best regards,
Marcelo.
