### ISSUE TITLE
1.8.3 broke ABI without changing SONAME

### ISSUE THREAD

**Issue by jcowgill** [mrjimenez/pupnp#57]
This change in 1.8.3 broke the ABI and therefore the SONAME should have been changed (ie: age reset to 0):
```diff
 EXPORT_SPEC int UpnpAddVirtualDir(
        /*! [in] The name of the new directory mapping to add. */
-       const char *dirName);
+       const char *dirName,
+       /*! [in] The cookie to associated with this virtual directory */
+       const void *cookie,
+       /*! [out] The cookie previously associated, if mapping is already present */
+       const void **oldcookie);
```

If only the `cookie` argument was added, you could probably get away with this because all that would happen is that a garbage value is passed around without being used. With the addition of `oldcookie`, any old programs will not initialise this value and will probably segfault when libupnp tries to write to it.

**Comment by mrjimenez** [comment]
Hi James,

I agree with your considerations.

I believe the only way to fix it is to do a new release. Does anyone have a better suggestion?

Best regards,
Marcelo.

**Comment by jcowgill** [comment]
Please can you make a release containing this change.

I'm apprehensive about uploading the ABI bump to Debian before 1.8.4 is released in case any other ABI breaking changes are made in the meantime (which would end up with some unholy ABI fork...).

**Comment by ukleinek** [comment]
I though we could smooth this a bit by things like:

    #define UpnpAddVirtualDir(x) UpnpAddVirtualDir(x, NULL, NULL)

but this doesn't work unfortunately. Not sure there is something more clever that fulfills the purpose.

**Comment by mrjimenez** [comment]
Hi James,

Just released a new release.

Best regards,
Marcelo.

**Comment by ffontaine** [comment]
Dear Marcelo,

Could you also publish it on https://sourceforge.net/projects/pupnp/files/pupnp/?

Best Regards,
Fabrice

**Comment by mrjimenez** [comment]
Sure, in fact I have just did that.

Regards,
Marcelo.

**Comment by jcowgill** [comment]
Thanks a lot!
