### ISSUE TITLE
Latest released version is 1.6.25, but 'git describe' shows that the current version is 1.8.3-12-gb09afb0

### ISSUE THREAD

**Issue by yurivict** [mrjimenez/pupnp#71]
It's like 1.8.3 has never been released and has been released at the same time.
Something wasn't tagged or released right.

**Comment by ukleinek** [comment]
The latest release on the 1.6 branch is 1.6.25, and when `git-describe`ing this branch you get `release-1.6.25-3-g940335d6b7a5` which looks ok.

**Comment by yurivict** [comment]
So it seems like the latest version is 1.8.3, but it just isn't shown on GitHub or SourceForge.

**Comment by ffontaine** [comment]
1.8.3 is not the "latest" version.
For the time being, both branches (1.6.x and 1.8.x) will continue to be maintained.

**Comment by yurivict** [comment]
Ok.
Please make a release then in the 1.6.x branch that has pdfs.

**Comment by ffontaine** [comment]
Yes, we'll keep #72 opened and close this one as well as #73
