### ISSUE TITLE
1.8: GPL List code

### ISSUE THREAD

**Issue by v00d00** [mrjimenez/pupnp#77]
See https://github.com/mrjimenez/pupnp/commit/b15969ce71eca7757c1fd958612ab6b87c080996#comments for context.

What is the plan? 

1. Find another BSD licenced list implementation
2. Revert to 1.6 list implementation
3. Other?

**Comment by v00d00** [comment]
I personally think number 2 is the best option here, but we should wrap it in some template magic?

**Comment by mrjimenez** [comment]
Was there a 1.6 list implementation? As far as I know, this was the only list implementation that has existed. We need a BSD list implementation, since anything I can write now will certainly be tainted.

**Comment by mrjimenez** [comment]
I don't know if that means anything relative to licensing issues, but that particular file (list.h) has no GPL header. Also, the code is too simple to make it a license issue, I think that GPL has some provision in that regard about "too simple code".

**Comment by v00d00** [comment]
In 1.6 ThreadUtil's LinkedList.h and FreeList.h where "public".
