### ISSUE TITLE
Homebrew Formula for pupnp

### ISSUE THREAD

**Issue by elmodaddyb** [mrjimenez/pupnp#80]
Hello,

This issue is to determine the interest level of the **pupnp** team to have a macOS Homebrew formula to install the upnp library into macOS.

### Background

I work on [Gerbera UPnP media server](https://github.com/gerbera) which uses the **pupnp** library for support.  We would like to [create a Homebrew formula](https://github.com/gerbera/gerbera/issues/286) to make it easy for installation on macOS.  Since **pupnp** is a dependency, it seems reasonable to create a Homebrew formula for the library as well.

### Request

I created an [initial pupnp Homebrew formula](https://gist.github.com/elmodaddyb/a7947ee61d05a5bdd137ba564fcb1898#file-pupnp-rb), but would request your approval before pursuing such an addition to Homebrew project.

**Comment by mrjimenez** [comment]
Hi Eamonn,

I am not a Mac dev, so I am not familiar with Homebrew, so please correct me if I misunderstood something.

What exactly do you need our approval of? You want to include some kind of script to ease installation on Mac? Seems very interesting to me, I have no objections to include it.

Regards,
Marcelo.

**Comment by elmodaddyb** [comment]
I found that there is an existing homebrew formula for [libupnp](https://github.com/Homebrew/homebrew-core/blob/3f718e0da6173a38a654777cc454c9b16cf7051d/Formula/libupnp.rb).

I plan to update the `libupnp` formula with `1.8.3` version.
