### ISSUE TITLE
LFS issue on 32-bit Linux systems

### ISSUE THREAD

**Issue by whitefalk** [mrjimenez/pupnp#81]
Hi,

After testing pupnp 1.8.3 with gerbera 1.2.0 I found that on 32-bit linux (x86 and ARM) files larger than 2GB are played to the point in time, where the 2GB is reached.
Since the issue is not present on AMD64 my suspects were size_t and long long int.

My suspicion it that the following lines cause the issue:
https://github.com/mrjimenez/pupnp/blob/23f1d9346586ab815ce6ca9634e1e6d8064922ec/upnp/src/genlib/net/http/httpreadwrite.c#L448
(amount_to_be_read should be off_t instead of size_t)
https://github.com/mrjimenez/pupnp/blob/23f1d9346586ab815ce6ca9634e1e6d8064922ec/upnp/src/genlib/net/http/httpreadwrite.c#L468
(ReadSendSize is off_t and is cast down size_t)

It may be that other steps need to be taken, I changed Data_Buf_Size also to off_t.
It seems to work now.

The issue was probably introduced in 2010 with https://github.com/mrjimenez/pupnp/commit/9e7e7e3b890556cbfb3008c4f4f19f144cbb879f

Cheers,
wh

**Comment by ukleinek** [comment]
Do you care enough to create a pull request fixing that?

**Comment by whitefalk** [comment]
Yes, sure. I'm new to git(hub) so let's say... on the weekend I'll do it.
