### ISSUE TITLE
Breaking the API in a minor release

### ISSUE THREAD

**Issue by medoc92** [mrjimenez/pupnp#90]
The 1.8 API was changed between 1.8.2 and 1.8.3 (new parameters to the VDCallBack functions).

Making life difficult for developers is not going to encourage the use of this library.

I really wished that this kind of change could be discussed before it is committed.

**Comment by v00d00** [comment]
This was discussed in #57, accidents happen and I'm sure the maintainers will be more vigilant in future.

**Comment by mrjimenez** [comment]
> The 1.8 API was changed between 1.8.2 and 1.8.3 (new parameters to the VDCallBack functions).
> 
> Making life difficult for developers is not going to encourage the use of this library.
> 
> I really wished that this kind of change could be discussed before it is committed.

And in fact, it can be discussed even after it has been committed. It takes some time before a commit becomes a release. And even these are not set in stone.

Regards,
Marcelo.

**Comment by medoc92** [comment]
See https://github.com/mrjimenez/pupnp/issues/93 for a more general discussion.
