### ISSUE TITLE
upnpdebug module is not well-behaved

### ISSUE THREAD

**Issue by medoc92** [mrjimenez/pupnp#95]
There is quite a lot of weirdness in the current debug log module:

* Will try to create some output files if the application is not careful to prevent it.
* At least part of the output goes to stdout by default
* Multiple calls to UpnpInitLog() will lose file pointers 
* A call to UpnpCloseLog() may crash or close stdout/stderr depending on the current state of things
* The level of each message is not printed to the log so that you can't filter the output on the value
* Etc. 

Also a question: does anybody know what DEBUG_TARGET is meant for ? I can't make sense of it.

I understand that some of these things (for example using stdout) may be a question of taste, so I submit the following specification for discussion only for now:

* Write nothing and create no files by default (or, alternatively, write errors to stderr, please state pref).
* Accept any sequence of init/close/print without crashing or leaking resources.
* Never ever write anything to stdout, the app may use it to pipe stuff out (imho everybody expects the garbage to go to stderr).
* Use a single file with enough data in each message to enable filtering what you want. Using 2 files is unnecessary and makes it difficult to relate errors and debug messages.
* Minimum change to the message format (add level and target), in a way unlikely to confuse a hypothetical existing parser.
* No change to the API, except that some some parameters may be ignored (e.g. the 2nd file name).

Nothing urgent, but I hope that someone will care to comment... Obviously I volunteer to implement the changes.

**Comment by mrjimenez** [comment]
Hi Jean-Francois,

- Ideally nothing from within the library should go to stdout. The app is free to do whatever it wants.
- Debug stuff currently go to two files: libupnp_err.log and libupnp_info.log. The idea is that when debug is enabled, the info file gets very large, so the err file gets the detected error problems. The info file is there to debug several parts of the protocol itself. Maybe we could find a reasonable way to configure runtime module level debug, currently I believe this is a compile time option only.
- Crashing or leaking should never happen. A debug feature that introduces a bug sounds more like a bug feature.
- Using a single file: nothing against it. Just make sure there is an easy string to search for an error in that file, which has traditionally been huge.
- "Minimum change to the message format (add level and target), in a way unlikely to confuse a hypothetical existing parser." -> sounds great. I doubt there is a parser, but I would be pleased to know that.
- "No change to the API, except that some some parameters may be ignored (e.g. the 2nd file name)."-> I'm ok with that.

Best regards,
Marcelo.
